version: '3'

services:
   db:
     container_name: wp-mysql
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: lrbo

   lrbo:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./lrbo:/var/www/html/wp-content/themes/lrbo
       - ./plugin:/var/www/html/wp-content/plugins
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_NAME: lrbo
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: password
       WORDPRESS_CONFIG_EXTRA: |
          define( 'WP_DEBUG', true );
          define( 'WP_DEBUG_LOG', true );
          define( 'WP_DEBUG_DISPLAY', false );
          @ini_set('display_errors',0);
          @ini_set("error_log", dirname(__FILE__).'/wp-content/debug.log');

volumes:
    db_data:
